@echo off

start cmd /k "python supplier.py"
start cmd /k "python product_stock.py"
start cmd /k "python warehouse.py"
start cmd /k "python line.py 0 0"
start cmd /k "python line.py 1 0"
start cmd /k "python line.py 2 0"
start cmd /k "python line.py 3 0"
start cmd /k "python line.py 4 0"
start cmd /k "python line.py 0 1"
start cmd /k "python line.py 1 1"
start cmd /k "python line.py 2 1"
start cmd /k "python line.py 3 1"
start cmd /k "python line.py 4 1"
start cmd /k "python line.py 5 1"
start cmd /k "python line.py 6 1"
start cmd /k "python line.py 7 1"
start cmd /k "python factory.py empurrada 0 5 48"
start cmd /k "python factory.py puxada 1 8 48"
